### PR TITLE
Update README with easier user creation method

### PR DESCRIPTION
**Pull request by EricZeiberg**
A much easier way to create the initial user is to have rails do all the hard work. I've updated the README so that the instructions specify how to add the initial user without having to setup Bungees and servers and go through the normal registration process.

### CODE REVIEW

**Comment by jedediah** [comment]
Problem is the user won't have a UUID, so many things will be broken.

**Comment by EricZeiberg** [comment]
Well you could lookup your own UUID and manually set it

**Comment by EricZeiberg** [comment]
Would just setting the `uuid` field to your own UUID work?

**Comment by jedediah** [comment]
You should also call `User.refresh_username!` to get the username from Mojang

**Comment by jedediah** [comment]
Just chain `confirm!` onto `create!`, no need to call `save!` at all. Besides that, looks good.

**Comment by jedediah** [comment]
Maybe some nicer formatting for the argument list too?

Also, there's a typo at `"uuid"`

**Pull request merged**
